/*
Horoscope API

The Horoscope API offers a versatile solution for accessing daily, weekly, and monthly horoscope predictions tailored to each zodiac sign. With intuitive endpoints and a straightforward interface, developers can seamlessly integrate astrological insights into their applications. Whether providing users with daily guidance, weekly trends, or monthly forecasts, this API delivers accurate and personalized horoscope data in JSON format. Built on reliable infrastructure, the API ensures scalability and reliability, enabling it to handle varying levels of demand with minimal downtime. With customizable parameters, developers can fine-tune requests to meet specific requirements, enhancing user experiences with tailored astrological content. Comprehensive documentation accompanies the API, providing developers with all the information needed to integrate horoscope data seamlessly. Start leveraging the Horoscope API today to empower users with personalized astrological insights that resonate with their individual zodiac signs and life experiences.

API version: 2.0.2
Contact: ashutoshbritish@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"net/http"
)

// APIResponse stores the API response returned by the server.
type APIResponse struct {
	*http.Response `json:"-"`
	Message        string `json:"message,omitempty"`
	// Operation is the name of the OpenAPI operation.
	Operation string `json:"operation,omitempty"`
	// RequestURL is the request URL. This value is always available, even if the
	// embedded *http.Response is nil.
	RequestURL string `json:"url,omitempty"`
	// Method is the HTTP method used for the request.  This value is always
	// available, even if the embedded *http.Response is nil.
	Method string `json:"method,omitempty"`
	// Payload holds the contents of the response body (which may be nil or empty).
	// This is provided here as the raw response.Body() reader will have already
	// been drained.
	Payload []byte `json:"-"`
}

// NewAPIResponse returns a new APIResponse object.
func NewAPIResponse(r *http.Response) *APIResponse {

	response := &APIResponse{Response: r}
	return response
}

// NewAPIResponseWithError returns a new APIResponse object with the provided error message.
func NewAPIResponseWithError(errorMessage string) *APIResponse {

	response := &APIResponse{Message: errorMessage}
	return response
}
