openapi: 3.0.1
info:
  contact:
    email: ashutoshbritish@gmail.com
    name: Ashutosh Krishna
    url: https://ashutoshkrris.in
  description: "The Horoscope API offers a versatile solution for accessing daily,\
    \ weekly, and monthly horoscope predictions tailored to each zodiac sign. With\
    \ intuitive endpoints and a straightforward interface, developers can seamlessly\
    \ integrate astrological insights into their applications. Whether providing users\
    \ with daily guidance, weekly trends, or monthly forecasts, this API delivers\
    \ accurate and personalized horoscope data in JSON format. Built on reliable infrastructure,\
    \ the API ensures scalability and reliability, enabling it to handle varying levels\
    \ of demand with minimal downtime. With customizable parameters, developers can\
    \ fine-tune requests to meet specific requirements, enhancing user experiences\
    \ with tailored astrological content. Comprehensive documentation accompanies\
    \ the API, providing developers with all the information needed to integrate horoscope\
    \ data seamlessly. Start leveraging the Horoscope API today to empower users with\
    \ personalized astrological insights that resonate with their individual zodiac\
    \ signs and life experiences."
  license:
    name: MIT
  title: Horoscope API
  version: 2.0.2
servers:
- url: /api/v1
tags:
- description: Horoscope APIs
  name: /
paths:
  /get-horoscope/daily:
    get:
      operationId: get_daily_horoscope_api
      parameters:
      - in: query
        name: sign
        required: true
        schema:
          type: string
      - description: "Accepted values: Date in format (YYYY-MM-DD) OR \"TODAY\" OR\
          \ \"TOMORROW\" OR \"YESTERDAY\"."
        in: query
        name: day
        schema:
          default: TODAY
          type: string
      responses:
        "200":
          content: {}
          description: Success
      tags:
      - /
  /get-horoscope/monthly:
    get:
      operationId: get_monthly_horoscope_api
      parameters:
      - in: query
        name: sign
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Success
      tags:
      - /
  /get-horoscope/weekly:
    get:
      operationId: get_weekly_horoscope_api
      parameters:
      - in: query
        name: sign
        required: true
        schema:
          type: string
      responses:
        "200":
          content: {}
          description: Success
      tags:
      - /
components:
  responses:
    ParseError:
      content: {}
      description: When a mask can't be parsed
    MaskError:
      content: {}
      description: When any error occurs on mask
  schemas: {}
x-original-swagger-version: "2.0"
